name: Mechanix
author: Etho5
main: com.etho5.mechanix.Main
description: Machines and shit.
version: 0.0.1
api-version: 1.16
commands:
  mechanix:
    description: Base command for Mechanix. Includes GUIDE, RECIPE, and GIVE subcommands.
    usage: /<command>
    aliases: mech
permissions:
  mechanix.*:
    description: Allows for use of all Mechanix commands.
    default: op
    children:
      mechanix.give: true
  mechanix.give:
    description: Gives a designated playe a specified Mechanix item.
    default: op